### ISSUE TITLE
[USER-STORY] Multiple options

### ISSUE THREAD

**Issue by Sporgl** [MetroCS/cs3250_practice#85] opened 2024-10-16 22:06 UTC
# User Story

## Story
As an end user <br>
I want to see multiple decision outcomes<br>
so that I can have multiple choices as a decision aid

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* It Displays multiple outcomes
* Each outcome must be related to 
* All outcomes must be different

### Scenario 1
**Given**  User input (options, criteria)
**when**  Enter Button is pressed (input is submitted)
**then**  Multiple outcomes are presented

### Dependents  
Relative Ranking of Decision Outcomes ==> https://github.com/MetroCS/cs3250_practice/issues/53

**Comment by jody** [comment] 2024-10-21 01:55
What is the relationship between this issue and #83 ?

The second rule, "Each outcome must be related to", appears to be missing a specification as to what the outcome is related.

The scenario seems to over-specify a design choice of using "Enter Button". (For example, why isn't a keypress OK?)

**Comment by jody** [comment] 2024-10-21 01:56
Marking as duplicate of #83 for now. Can update when author responds.

**Comment by Sporgl** [comment] 2024-10-22 01:12
closed due to misunderstanding

**Closed** 2024-10-28 00:06 UTC
Labels: duplicate, question, triage
